project_name: five-hunerd
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
archives:
  replacements:
    linux: Linux
    windows: Windows
    darwin: Darwin
    386: i386
    amd64: x86_64
